---
- name: Converge
  hosts: all
  become: true
  roles:
    - role: ansible-role-beats
      products:
        - filebeat
        - metricbeat
        - packetbeat
        - auditbeat
        - heartbeat
